version: '3'
services:
    app:
        container_name: arive
        restart: always
        build: .
        ports:
            - '3002:3002'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
